name: Build IPK OpenWRT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget tar

    - name: Compile IPK and Clone luci-app-alpha-config repository
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        git clone -b master https://github.com/${{ github.repository }}.git package/luci-app-alpha-config
        make package/luci-app-alpha-config/compile V=s

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ipk-artifacts
        path: bin/packages/x86_64/
