name: Build IPK OpenWRT

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenWRT SDK
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python

    - name: Prepare feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile IPK and Clone luci-app-alpha-config repository
      run: |
        git clone -b master https://github.com/${{ github.repository }}.git package/downloads/luci-app-alpha-config
        make package/luci-app-alpha-config/compile V=s

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ipk-artifacts
        path: bin/packages/x86_64/
