name: Build IPK OpenWRT

on:
  push:
    branches:
      - master
    paths:
      - 'luci-app-alpha-config/Makefile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenWRT SDK
      uses: openwrt-compat/openwrt-sdk-action@v1
      with:
        version: 21.02
        profile: x86_64
        feeds-update: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget tar

    - name: Prepare feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile IPK
      run: |
        make package/luci-app-alpha-config/compile V=s

    - name: Upload IPK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ipk-artifacts
        path: bin/packages/x86_64/
